import gc
import logging
import os
import tomllib

import numpy as np
import pandas as pd
import torch
import transformers
from huggingface_hub.utils import disable_progress_bars
from rich.console import Console
from rich.panel import Panel
from rich.progress import BarColumn, Progress, SpinnerColumn, TaskProgressColumn, TextColumn

from src.blender import ScoreBlender
from src.config_utils import fail_on_model_error
from src.evaluate import compute_metrics
from src.llm_verifier import GemmaVerifier
from src.preprocess import main as run_preprocess
from src.rag import BanglaRAG

# Suppress Hugging Face warnings/load reports for a cleaner UI
transformers.utils.logging.set_verbosity_error()
transformers.utils.logging.disable_progress_bar()
disable_progress_bars()
logging.getLogger("transformers").setLevel(logging.ERROR)

console = Console()


def build_rag_query(row, query_mode):
    if query_mode == "prompt_response":
        return f"{row['prompt_bn']} {row['response_bn']}"
    return str(row["prompt_bn"])


def main():
    console.print(
        Panel(
            "[bold yellow]Start Training & Optimization Pipeline[/bold yellow]",
            border_style="bold yellow",
        )
    )

    with open("configs/config.toml", "rb") as f:
        config = tomllib.load(f)

    # 1. Preprocess raw data
    train_processed_path = os.path.join(config["data"]["processed_dir"], "train.csv")
    train_evidence_path = os.path.join(config["data"]["processed_dir"], "train_with_evidence.csv")

    if os.path.exists(train_evidence_path):
        console.print(
            f"[bold green]Found existing {train_evidence_path}. Loading cached contexts...[/bold green]"
        )
        train_df = pd.read_csv(train_evidence_path)
    else:
        if not os.path.exists(train_processed_path):
            console.print("[yellow]Processed files not found. Executing preprocessing...[/yellow]")
            run_preprocess()

        train_df = pd.read_csv(train_processed_path)

        # 2. RAG retrieval for NULL-context rows
        console.print("\n[bold cyan]Step 1: Context Evidence Retrieval[/bold cyan]")
        null_mask = train_df["context"] == "[NULL]"
        num_nulls = null_mask.sum()

        if num_nulls > 0:
            index_path = config["rag"]["index_path"]
            query_mode = config["rag"].get("query_mode", "prompt")
            if os.path.exists(index_path):
                console.print(
                    f"Dense RAG index found. Retrieving evidence for [bold yellow]{num_nulls}[/bold yellow] NULL-context rows..."
                )
                rag = BanglaRAG()
                rag.load_index()

                retrieved_contexts = []
                with Progress(
                    SpinnerColumn(),
                    TextColumn("[progress.description]{task.description}"),
                    BarColumn(),
                    TaskProgressColumn(),
                    transient=True,
                ) as progress:
                    task = progress.add_task(description="Retrieving facts...", total=num_nulls)
                    for idx, row in train_df[null_mask].iterrows():
                        query = build_rag_query(row, query_mode)
                        chunks = rag.retrieve(query)
                        if chunks:
                            retrieved_contexts.append(" ".join(chunks))
                        else:
                            retrieved_contexts.append("[NULL]")
                        progress.advance(task)

                train_df.loc[null_mask, "context"] = retrieved_contexts
                console.print("[green]✔ Context evidence retrieval complete.[/green]")
            else:
                console.print(
                    f"[bold red]WARNING: Dense RAG index not found at {index_path}.[/bold red]"
                )
                console.print(
                    "NULL-context rows will remain ungrounded. Build the RAG index if a corpus is available."
                )

        os.makedirs(config["data"]["processed_dir"], exist_ok=True)
        train_df.to_csv(train_evidence_path, index=False)

    # 3. Train XLM-RoBERTa Cross-Encoder
    console.print("\n[bold cyan]Step 2: Training XLM-RoBERTa Cross-Encoder[/bold cyan]")

    # Run XLM-R CV in a separate python process using subprocess to guarantee GPU memory is fully released
    import subprocess
    import sys

    cmd = [
        sys.executable,
        "-c",
        "import tomllib, pandas as pd; "
        "from src.xlmr_encoder import train_cross_validation; "
        "config = tomllib.load(open('configs/config.toml', 'rb')); "
        "train_df = pd.read_csv('dataset/processed/train_with_evidence.csv'); "
        "train_cross_validation(train_df, config)",
    ]

    console.print("[cyan]Spawning subprocess for XLM-R training...[/cyan]")
    proc = subprocess.run(cmd)
    if proc.returncode != 0:
        raise RuntimeError("XLM-R training subprocess failed.")

    # Load predictions generated by the XLM-R subprocess
    oof_path = os.path.join(config["data"]["processed_dir"], "oof_xlmr.csv")
    if os.path.exists(oof_path):
        train_df = pd.read_csv(oof_path)
        p_xlmr = train_df["p_xlmr"].values
    else:
        raise RuntimeError(f"XLM-R training subprocess failed: {oof_path} was not created.")

    # Clean up GPU memory
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()

    # 4. Predict using Gemma 4 Verifier
    console.print("\n[bold cyan]Step 3: Generating Gemma 4 Verifier Scores[/bold cyan]")

    if config.get("runtime", {}).get("use_llm_verifier", True):
        verifier = GemmaVerifier()
        console.print("\n[bold cyan]Building Dynamic Few-Shot Exemplar Index...[/bold cyan]")
        verifier.exemplar_retriever.build_index(train_df)
        try:
            verifier.load_model()
            p_llm, is_c0, is_c1, is_c2 = verifier.predict_dataset(train_df)
        except Exception as e:
            if fail_on_model_error(config):
                raise RuntimeError(
                    "Gemma verifier failed; refusing to train on fake scores."
                ) from e
            console.print(f"[bold red]Failed to run Gemma verifier: {e}[/bold red]")
            console.print(
                "[yellow]Falling back to XLM-R-only scores because fail_on_model_error=false.[/yellow]"
            )
            p_llm = p_xlmr.copy()
            is_c0 = np.zeros(len(train_df))
            is_c1 = np.zeros(len(train_df))
            is_c2 = np.zeros(len(train_df))
    else:
        console.print("[yellow]LLM verifier disabled. Using XLM-R-only blend features.[/yellow]")
        p_llm = p_xlmr.copy()
        is_c0 = np.zeros(len(train_df))
        is_c1 = np.zeros(len(train_df))
        is_c2 = np.zeros(len(train_df))

    train_df["p_llm"] = p_llm
    train_df["is_c0"] = is_c0
    train_df["is_c1"] = is_c1
    train_df["is_c2"] = is_c2
    train_df.to_csv(
        os.path.join(config["data"]["processed_dir"], "train_with_preds.csv"), index=False
    )

    # 5. Fit Meta-Classifier Blender
    console.print("\n[bold cyan]Step 4: Training Meta-Classifier Blender[/bold cyan]")
    y_true = train_df["label"].values
    p_xlmr = train_df["p_xlmr"].values
    p_llm = train_df["p_llm"].values

    blender = ScoreBlender()

    with Console().status("Training Meta-Classifier...", spinner="simpleDots"):
        blender.fit(
            y_true,
            p_xlmr,
            p_llm,
            has_context=train_df["has_context"].values,
            is_c0=train_df["is_c0"].values,
            is_c1=train_df["is_c1"].values,
            is_c2=train_df["is_c2"].values,
            threshold_metric=config.get("blender", {}).get("threshold_metric", "macro_f1"),
        )
    blender.save()

    # 6. Evaluation metrics
    console.print("\n[bold cyan]Step 5: Overall Pipeline Performance[/bold cyan]")
    p_blend, preds = blender.predict(
        p_xlmr,
        p_llm,
        has_context=train_df["has_context"].values,
        is_c0=train_df["is_c0"].values,
        is_c1=train_df["is_c1"].values,
        is_c2=train_df["is_c2"].values,
    )
    compute_metrics(y_true, preds)

    console.print(
        Panel(
            "[bold green]Training Pipeline Successfully Finished![/bold green]",
            border_style="bold green",
        )
    )


if __name__ == "__main__":
    main()
